inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '*.gemspec'
    - '**/*.rake'
  Exclude:
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentArray:
  EnforcedStyle: consistent
  IndentationWidth: 4

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Layout/IndentHash:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentAssignment:
  IndentationWidth: 4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - db/schema.rb

Metrics/LineLength:
#  Max: 100
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
